# Introduction

Write the command `print('Hello world')` in the cell below and execute it by pressing `Shift` + `Enter`

In [1]:
#write answer here

Let's now make this slightly mor interesting by creating our first variable. Write any message in the variable in the cell bellow and execute the cell. Note that the code below includes comments which follow the `#` mark

In [2]:
message = '' # Write any string you want displayed between the quotation marks
print(message)

As you can see, cells can contain any number of lines of code. You can always add a new line into a cell by pressing the `Enter` key.

As you might have already guessed, variables and variable types do not need to be declared/defined beforehand; Python automatically assigns a type to a variable as it is being used, making it very easy to change a variable type. Try executing the following cell and see the different data types available in Python:

In [3]:
# String
my_variable = 'I know Kung-Fu'
print(type(my_variable))

# Int
my_variable = 2025
print(type(my_variable))

# Float
my_variable = 3.14
print(type(my_variable))

# List
my_variable = ['a', 'b', 1, 2]
print(type(my_variable))

# Tuple
my_variable = ('a', 'b', 1, 2)
print(type(my_variable))

# Dictionary
my_variable = {'a': 1, 'b': 2}
print(type(my_variable))

<class 'str'>
<class 'int'>
<class 'float'>
<class 'list'>
<class 'tuple'>
<class 'dict'>

A third numerical data type, complex, is also available but we will not explore it in this course

## Data types

### Strings

Let's do some basic operations with strings

#### Concatenation

In [4]:
setup = 'I am the '
punch1 = 'terror that flaps in the night!'
punch2 = 'tenor that sings in the night!'
punch3 = 'metal key on the sardine can of justice!'
punch4 = 'wrong number that wakes you at 3am!'

print(setup + punch3)

I am the metal key on the sardine can of justice!

#### Repetition

In [5]:
lyric = "It's the end of the world as we know it "

lyric*3

"It's the end of the world as we know it It's the end of the world as we know it It's the end of the world as we know it "

#### Slicing

In [6]:
name = 'Pink Floyd'

In [7]:
print(name[2])
print(name[-3])
print(name[:6])
print(name[2:])
print(name[:-2])
print(name[-3:])
print(name[2:6])
print(name[6:-2])

n
o
Pink F
nk Floyd
Pink Flo
oyd
nk F
lo

### Numbers

In [8]:
x = 5
y = 2

In [9]:
# addition
x + y

7

In [10]:
# subtraction
y - x

-3

In [11]:
# multiplication
x*y

10

In [12]:
# exponent
x**y

25

In [13]:
# division
x/y

2.5

In [14]:
# floor division
x//y

2

In [15]:
# modulus
x%y

1

In [16]:
# Comparisons:
print(x==y)
print(x!=y)
print(x>y)
print(x>=y)
print(x<y)
print(x<=y)

False
True
True
True
False
False

In [17]:
# Booleans:
print(x==y and x!=y)
print(x==y or x!=y)
print(not x==y)
print(not x!=y)

False
True
True
False

### Lists, tuples and dictionaries

Lists, tuples and dictionaries can contain any type of data:

In [18]:
my_list = ['cat', 4, 4.8, ('chicken', 'fish'), ['couch', 'stairs', 'window']]
my_tuple = ('cat', 4, 4.8, ('chicken', 'fish'), ['couch', 'stairs', 'window'])
my_dict = {'pet': 'cat', 'age': 4, 'weight': 4.8, 'food': ('chicken', 'fish'), 'fav_spots': ['couch', 'stairs', 'window']}

Lists can be modified:

In [19]:
print(my_list)
my_list[2] = 4.7
print(my_list)

['cat', 4, 4.8, ('chicken', 'fish'), ['couch', 'stairs', 'window']]
['cat', 4, 4.7, ('chicken', 'fish'), ['couch', 'stairs', 'window']]

Tuples cannot:

In [20]:
#my_tuple[2] = 4.7

Lists can also be concatenated:

In [21]:
my_list + ['something cat related', 'some other cat related thing']

['cat',
 4,
 4.7,
 ('chicken', 'fish'),
 ['couch', 'stairs', 'window'],
 'something cat related',
 'some other cat related thing']

Dictionaries use key identifiers for their values:

In [22]:
clue_solution = {
    'character': 'Miss Scarlett',
    'room': 'Ballroom',
    'weapon': 'Lead pipe'
}

In [23]:
clue_solution['character']

'Miss Scarlett'

To see all keys:

In [24]:
clue_solution.keys()

dict_keys(['character', 'room', 'weapon'])

To see all values:

In [25]:
clue_solution.values()

dict_values(['Miss Scarlett', 'Ballroom', 'Lead pipe'])

## Conditionals and loops

### if, elif, else

In [26]:
x = 5  # change x in your code to see the effect
if x < 0:
    print("negative")
elif x == 0:
    print("zero")
else:
    print("positive")

positive

### while

In [27]:
n = 0
while n < 10:
    n += 1
    print(n)
print("Finished")

1
2
3
4
5
6
7
8
9
10
Finished

### for

`for` loop over a range of numbers:

In [28]:
for i in range(5):
    print(i)

0
1
2
3
4

`for` loop over a string:

In [29]:
for letter in 'I know Kung-Fu':
    print(letter)

I

k
n
o
w

K
u
n
g
-
F
u

`for` loop over a list:

In [30]:
beatles = ['John', 'Paul', 'George', 'Ringo']

In [31]:
for beatle in beatles:
    print(beatle)

John
Paul
George
Ringo

### List comprehensions

Let's imagine we want a list of the squares all the even numbers in a range

In [32]:
list_of_squares = []
for i in range(10):
    if i%2 == 0:
        list_of_squares.append(i**2)
list_of_squares

[0, 4, 16, 36, 64]

In [33]:
list_of_squares = [i**2 for i in range(10) if i%2 == 0]
list_of_squares

[0, 4, 16, 36, 64]

## Functions

In [34]:
def make_list(length, exponent):
    list_of_exponents = [i**exponent for i in range(length) if i%2 == 0]
    return list_of_exponents

In [35]:
make_list(20, 3)

[0, 8, 64, 216, 512, 1000, 1728, 2744, 4096, 5832]

### Excercise

Create a function that outputs the multiplication table of a given number (parameter) as a list of tuples. For instance, the output of the table of 3 should look like this:
`[(1, 3),
 (2, 6),
 (3, 9),
 (4, 12),
 (5, 15),
 (6, 18),
 (7, 21),
 (8, 24),
 (9, 27),
 (10, 30)]`

In [36]:
# write answer here

# Data analysis

## Pandas

Let's start importing the Pandas package

In [37]:
import pandas as pd

We will use data of Covid-19 from WHO:
https://srhdpeuwpubsa.blob.core.windows.net/whdh/COVID/WHO-COVID-19-global-daily-data.csv
We can either download the CSV file and read it from disk or, in this case, we can load it directly from the source URL

In [38]:
url = 'https://srhdpeuwpubsa.blob.core.windows.net/whdh/COVID/WHO-COVID-19-global-daily-data.csv'
df = pd.read_csv(url) # We use the read_csv pandas function

Go ahead and see what the `df` variable looks like, simply type `df` in the cell below:

In [39]:
# write answer here

Pandas has read the data from the CSV file and returns what is called a DataFrame. We can see that Pandas has indexed the data and has recognised the CSV first line as headings. Let's limit the output to the first 5 lines using the `head()` method

In [40]:
df.head()

,Date_reported,Country_code,Country,WHO_region,New_cases,Cumulative_cases,New_deaths,Cumulative_deaths
0,2020-01-04,AF,Afghanistan,EMR,NaN,0,NaN,0
1,2020-01-04,DZ,Algeria,AFR,NaN,0,NaN,0
2,2020-01-04,AL,Albania,EUR,NaN,0,NaN,0
3,2020-01-04,AI,Anguilla,AMR,NaN,0,NaN,0
4,2020-01-04,AS,American Samoa,WPR,0.0,0,0.0,0

We can specify a different number of row to show from the top:

In [41]:
df.head(10)

,Date_reported,Country_code,Country,WHO_region,New_cases,Cumulative_cases,New_deaths,Cumulative_deaths
0,2020-01-04,AF,Afghanistan,EMR,NaN,0,NaN,0
1,2020-01-04,DZ,Algeria,AFR,NaN,0,NaN,0
2,2020-01-04,AL,Albania,EUR,NaN,0,NaN,0
3,2020-01-04,AI,Anguilla,AMR,NaN,0,NaN,0
4,2020-01-04,AS,American Samoa,WPR,0.0,0,0.0,0
5,2020-01-04,AM,Armenia,EUR,NaN,0,NaN,0
6,2020-01-04,AG,Antigua and Barbuda,AMR,NaN,0,NaN,0
7,2020-01-04,AZ,Azerbaijan,EUR,NaN,0,NaN,0
8,2020-01-04,AD,Andorra,EUR,NaN,0,NaN,0
9,2020-01-04,AT,Austria,EUR,NaN,0,NaN,0

The `tail()` method works just like the head function but it shows the last rows instead:

In [42]:
df.tail()

,Date_reported,Country_code,Country,WHO_region,New_cases,Cumulative_cases,New_deaths,Cumulative_deaths
593515,2026-10-11,AE,United Arab Emirates,EMR,NaN,1067030,NaN,2349
593516,2026-10-11,ZM,Zambia,AFR,NaN,349892,NaN,4078
593517,2026-10-11,TK,Tokelau,WPR,NaN,80,NaN,0
593518,2026-10-11,VI,United States Virgin Islands,AMR,NaN,25389,NaN,132
593519,2026-10-11,TZ,United Republic of Tanzania,AFR,NaN,43655,NaN,846

We can also check some basic information about this DataFrame:

In [43]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 593520 entries, 0 to 593519
Data columns (total 8 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Date_reported      593520 non-null  str
 1   Country_code       591047 non-null  str
 2   Country            593520 non-null  str
 3   WHO_region         593520 non-null  str
 4   New_cases          215481 non-null  float64
 5   Cumulative_cases   593520 non-null  int64
 6   New_deaths         156638 non-null  float64
 7   Cumulative_deaths  593520 non-null  int64
dtypes: float64(2), int64(2), str(4)
memory usage: 36.2 MB

More oftne than not we need to know the names of the columns. We can quickly see that with the `columns` attribute:

In [44]:
df.columns

Index(['Date_reported', 'Country_code', 'Country', 'WHO_region', 'New_cases',
       'Cumulative_cases', 'New_deaths', 'Cumulative_deaths'],
      dtype='str')

Sometimes we might want to know the datatypes of each column:

In [45]:
df.dtypes

Date_reported            str
Country_code             str
Country                  str
WHO_region               str
New_cases            float64
Cumulative_cases       int64
New_deaths           float64
Cumulative_deaths      int64
dtype: object

We can also quickly summarize the entire DataFrame using the `describe()` method:

In [46]:
df.describe()

          New_cases  Cumulative_cases     New_deaths  Cumulative_deaths
count  2.154810e+05      5.935200e+05  156638.000000       5.935200e+05
mean   3.617620e+03      2.255548e+06      45.443085       2.307256e+04
std    4.798536e+04      9.079619e+06     240.399960       9.089014e+04
min   -6.507900e+04      0.000000e+00   -3520.000000       0.000000e+00
25%    2.000000e+00      8.263000e+03       0.000000       5.600000e+01
50%    5.700000e+01      6.868200e+04       2.000000       8.350000e+02
75%    6.470000e+02      7.221118e+05      14.000000       8.784000e+03
max    6.966046e+06      1.034368e+08   44047.000000       1.239961e+06

### Important note:
We have casually seen three basic Pandas concepts: functions, methods and attributes. Functions reffer specifically to functions of the Pandas library, for instance the `pd.read_csv()` is a function of Pandas. Methods and Attributes are related to Pandas objects (DataFrames and Series), therefore the `df.info()` command is using the `info()` method on the `df` object, while the `df.columns` command is calling the `columns` attribute of the `df` object.

## Displaying data of specific columns

In [47]:
df['Country'].head()

0       Afghanistan
1           Algeria
2           Albania
3          Anguilla
4    American Samoa
Name: Country, dtype: str

In [48]:
df.Country.head()

0       Afghanistan
1           Algeria
2           Albania
3          Anguilla
4    American Samoa
Name: Country, dtype: str

In [49]:
df[['Country', 'WHO_region']]

                             Country WHO_region
0                        Afghanistan        EMR
1                            Algeria        AFR
2                            Albania        EUR
3                           Anguilla        AMR
4                     American Samoa        WPR
...                              ...        ...
593515          United Arab Emirates        EMR
593516                        Zambia        AFR
593517                       Tokelau        WPR
593518  United States Virgin Islands        AMR
593519   United Republic of Tanzania        AFR

[593520 rows x 2 columns]

## Displaying unique values of a column

In [50]:
df['WHO_region'].unique()

<StringArray>
['EMR', 'AFR', 'EUR', 'AMR', 'WPR', 'SEAR', 'OTHER']
Length: 7, dtype: str

## Selecting entries based on Boolean condition

Let's get a subset of all the data from Switzerland

In [51]:
df[df['Country'] == 'Switzerland']

,Date_reported,Country_code,Country,WHO_region,New_cases,Cumulative_cases,New_deaths,Cumulative_deaths
210,2020-01-04,CH,Switzerland,EUR,NaN,0,NaN,0
286,2020-01-05,CH,Switzerland,EUR,NaN,0,NaN,0
682,2020-01-06,CH,Switzerland,EUR,NaN,0,NaN,0
766,2020-01-07,CH,Switzerland,EUR,NaN,0,NaN,0
1162,2020-01-08,CH,Switzerland,EUR,NaN,0,NaN,0
...,...,...,...,...,...,...,...,...
592530,2026-10-07,CH,Switzerland,EUR,NaN,4492662,NaN,14170
592598,2026-10-08,CH,Switzerland,EUR,NaN,4492662,NaN,14170
593006,2026-10-09,CH,Switzerland,EUR,NaN,4492662,NaN,14170
593086,2026-10-10,CH,Switzerland,EUR,NaN,4492662,NaN,14170
593490,2026-10-11,CH,Switzerland,EUR,NaN,4492662,NaN,14170

In [52]:
df[df['Country'] == 'Switzerland']['Cumulative_cases'].head()

210     0
286     0
682     0
766     0
1162    0
Name: Cumulative_cases, dtype: int64

### Mini-exercise
Get a subset of all the data from Bolivia

In [53]:
# write answer here

### Another mini-exercise
Get a subset of all data with less than 1 million cumulative cases

In [54]:
# write answer here

### Multiple conditions

Let's get a subset of data where cumulative cases fall within 1 million and 2 million:

In [55]:
df[(df['Cumulative_cases'] > 1000000) & (df['Cumulative_cases'] < 2000000)].head()

,Date_reported,Country_code,Country,WHO_region,New_cases,Cumulative_cases,New_deaths,Cumulative_deaths
28029,2020-04-29,US,United States of America,AMR,23758.0,1006371,1489.0,58350
28085,2020-04-30,US,United States of America,AMR,23935.0,1030306,2111.0,60461
28505,2020-05-01,US,United States of America,AMR,26774.0,1057080,2417.0,62878
28565,2020-05-02,US,United States of America,AMR,31221.0,1088301,2238.0,65116
28985,2020-05-03,US,United States of America,AMR,33082.0,1121383,1953.0,67069

Now let's get a subset of two different WHO regions:

In [56]:
df[(df['WHO_region'] == 'EUR') | (df['WHO_region'] == 'AMR')].head()

,Date_reported,Country_code,Country,WHO_region,New_cases,Cumulative_cases,New_deaths,Cumulative_deaths
2,2020-01-04,AL,Albania,EUR,NaN,0,NaN,0
3,2020-01-04,AI,Anguilla,AMR,NaN,0,NaN,0
5,2020-01-04,AM,Armenia,EUR,NaN,0,NaN,0
6,2020-01-04,AG,Antigua and Barbuda,AMR,NaN,0,NaN,0
7,2020-01-04,AZ,Azerbaijan,EUR,NaN,0,NaN,0

Note that instead of using the `and` and `or` operands we use `&` and `|` respectively, which are the boolean operands in Pandas. Let's see other boolean conditions:

If we want any data of a specific list of WHO regions:

In [57]:
df[df['WHO_region'].isin(['EUR', 'AMR', 'WPR'])].head()

,Date_reported,Country_code,Country,WHO_region,New_cases,Cumulative_cases,New_deaths,Cumulative_deaths
2,2020-01-04,AL,Albania,EUR,NaN,0,NaN,0
3,2020-01-04,AI,Anguilla,AMR,NaN,0,NaN,0
4,2020-01-04,AS,American Samoa,WPR,0.0,0,0.0,0
5,2020-01-04,AM,Armenia,EUR,NaN,0,NaN,0
6,2020-01-04,AG,Antigua and Barbuda,AMR,NaN,0,NaN,0

If instead we want data not from those regions:

In [58]:
df[~df['WHO_region'].isin(['EUR', 'AMR', 'WPR'])].head()

,Date_reported,Country_code,Country,WHO_region,New_cases,Cumulative_cases,New_deaths,Cumulative_deaths
0,2020-01-04,AF,Afghanistan,EMR,NaN,0,NaN,0
1,2020-01-04,DZ,Algeria,AFR,NaN,0,NaN,0
12,2020-01-04,AO,Angola,AFR,NaN,0,NaN,0
14,2020-01-04,BT,Bhutan,SEAR,0.0,0,0.0,0
15,2020-01-04,BH,Bahrain,EMR,NaN,0,NaN,0

## Series operations

In [59]:
df['Cumulative_cases']+100

0             100
1             100
2             100
3             100
4             100
           ...
593515    1067130
593516     349992
593517        180
593518      25489
593519      43755
Name: Cumulative_cases, Length: 593520, dtype: int64

We can apply several operations to entire columns. Single columns in a Pandas DataFrame behave like Pandas Series which are essentially one-dimensional arrays as opposed to Pandas DataFrames which are two-dimensional arrays

In [60]:
# Arithmetic operations are applied to each data in the Series. Let's imagine we want to express cases per million
df['Cumulative_cases']/1000000

0         0.000000
1         0.000000
2         0.000000
3         0.000000
4         0.000000
            ...
593515    1.067030
593516    0.349892
593517    0.000080
593518    0.025389
593519    0.043655
Name: Cumulative_cases, Length: 593520, dtype: float64

In [61]:
# These operations are non-destructive:
df['Cumulative_cases']

0               0
1               0
2               0
3               0
4               0
           ...
593515    1067030
593516     349892
593517         80
593518      25389
593519      43655
Name: Cumulative_cases, Length: 593520, dtype: int64

We can also perform operations between columns, in which case the operation is aplied with each pair of ordered values:

In [62]:
df['Cumulative_cases']-df['Cumulative_cases']

0         0
1         0
2         0
3         0
4         0
         ..
593515    0
593516    0
593517    0
593518    0
593519    0
Name: Cumulative_cases, Length: 593520, dtype: int64

Notice how non of these operations are accomplished whithout the need of loops

### Mini-exercise
Choose a single country and calculate the Case Fatality Ratios (CFRs) for each date (CFR is the ratio of deaths to cases expressed in percentage). Use cumulative values.

In [63]:
# write answer here

## String operations with Pandas

We can also do iterable operations on a pandas string Series through the `str` accessor.

For instance, we can make all characters upper case:

In [77]:
df.Country.str.upper()

0                          AFGHANISTAN
1                              ALGERIA
2                              ALBANIA
3                             ANGUILLA
4                       AMERICAN SAMOA
                      ...
593515            UNITED ARAB EMIRATES
593516                          ZAMBIA
593517                         TOKELAU
593518    UNITED STATES VIRGIN ISLANDS
593519     UNITED REPUBLIC OF TANZANIA
Name: Country, Length: 593520, dtype: str

We can also use the `split` method to obtain a Series of string lists

In [78]:
df.Country.str.split(' ')

0                             [Afghanistan]
1                                 [Algeria]
2                                 [Albania]
3                                [Anguilla]
4                         [American, Samoa]
                        ...
593515             [United, Arab, Emirates]
593516                             [Zambia]
593517                            [Tokelau]
593518    [United, States, Virgin, Islands]
593519     [United, Republic, of, Tanzania]
Name: Country, Length: 593520, dtype: object

We can also chain several string methods one after the other using the `str`accessor:

In [79]:
df.Country.str.upper().str.split()

0                             [AFGHANISTAN]
1                                 [ALGERIA]
2                                 [ALBANIA]
3                                [ANGUILLA]
4                         [AMERICAN, SAMOA]
                        ...
593515             [UNITED, ARAB, EMIRATES]
593516                             [ZAMBIA]
593517                            [TOKELAU]
593518    [UNITED, STATES, VIRGIN, ISLANDS]
593519     [UNITED, REPUBLIC, OF, TANZANIA]
Name: Country, Length: 593520, dtype: object

## Time-Series data

Let's have a look at the datatypes:

In [64]:
df.dtypes

Date_reported            str
Country_code             str
Country                  str
WHO_region               str
New_cases            float64
Cumulative_cases       int64
New_deaths           float64
Cumulative_deaths      int64
dtype: object

We can see that the `Date_reported` column is of the `object` type. However, Pandas has a specific datatype that is more useful for time-series data: the Timestamp object. We'll use the Pandas `to_datetime` function to transform the data od the `Date_reported` column:

In [65]:
df['Date_reported'] = pd.to_datetime(df['Date_reported'])

In [66]:
df.dtypes

Date_reported        datetime64[us]
Country_code                    str
Country                         str
WHO_region                      str
New_cases                   float64
Cumulative_cases              int64
New_deaths                  float64
Cumulative_deaths             int64
dtype: object

## Grouping and aggregating data

Let's leave the cases and deaths data for the moment and look at some vaccination data instead. We'll use data from this URL: https://srhdpeuwpubsa.blob.core.windows.net/whdh/COVID/COV_VAC_UPTAKE_2024.csv . By now you should have the knowledge to load it on a variable named vac_df and check the first 5 rows.

In [67]:
vac_df = # complete code

In [68]:
vac_df.head()

We want to know the total number (globally) of vaccines administered per demographic group by the 1st quarter of 2024. Let's start filtering the data we need. Remember we're only interested in four columns: `YEAR`, `QUARTER`, `COVID_VACCINE_ADM_1D`, and `GROUP`.

In [69]:
cols = ['YEAR', 'QUARTER', 'COVID_VACCINE_ADM_1D', 'GROUP']

In [70]:
subset = vac_df[vac_df['QUARTER'] == 1][cols]

NameError: name 'vac_df' is not defined

In [ ]:
subset.head()

Now we will use the `groupby()` and the `agg()` methods

In [ ]:
subset.groupby('GROUP').agg('sum')

We used `'sum'` as the aggregation function because we needed total number of vaccines, however, the aggregation function affected all the other columns. We could of course ignore the other columns, but instead we will use different aggregation functions for each column passing the arguments in a dictionary:

In [ ]:
subset.groupby('GROUP').agg({'COVID_VACCINE_ADM_1D': 'sum', 'YEAR': 'max', 'QUARTER': 'max'})

### Not-so-mini-exercise
Go back to the cases and deaths dataset and display a grouped array of cumulative cases and deaths per WHO region. Think very carefully about the aggregation functions.

In [ ]:
# write answer here

# Data visualization

We will now use the data we've been seeing to create some plots. We will rely on the matplotlib library:

In [ ]:
import matplotlib.pyplot as plt

%matplotlib inline

Let's use the vaccination totals we obtained before to make our first plot:

In [ ]:
data = subset.groupby('GROUP').agg({'COVID_VACCINE_ADM_1D': 'sum', 'YEAR': 'max', 'QUARTER': 'max'})

Pyplot's `bar()` function takes two arguments to plot a bar chart: an array of categories for the X axis and an array of values for the Y axis. In this case we will use the DataFrame's indices for the X axis categories, and the COVID_VACCINE_ADM_1D totals for the Y axis values.

In [ ]:
plt.bar(data.index, data.COVID_VACCINE_ADM_1D)
plt.show()

This already looks good, but we can further improve it; for instance, we can add axis labels and a title:

In [ ]:
plt.bar(data.index, data.COVID_VACCINE_ADM_1D)

plt.ylabel('Total administered vaccines')
plt.xlabel('Demographic groups')
plt.title('Distribution of vaccines administered \n by demographic group')

plt.show()

A great thing about using Python for visualization is that we can use iterative operations to generate a large number of charts with little effort. Let's say we want to see the timeline of covid cases per WHO region.

In [ ]:
# Let's start by getting a list of the unique region names:
regions = df['WHO_region'].unique()
regions

In [ ]:
# Now let's create a loop that iterates over each region to plot total cases of each region over time:
for region in regions: 
    data = df[df['WHO_region']==region].groupby('Date_reported').agg('sum') # We aggregate by date
    plt.plot(data.index, data.Cumulative_cases) # We use the plot function

plt.show()

We can see that the timelines are plotted but we don't know which line belongs to which region. Let's add some arguments:

In [ ]:
for region in regions: 
    data = df[df['WHO_region']==region].groupby('Date_reported').agg('sum')
    plt.plot(data.index, data.Cumulative_cases, label=region) # the label argument lets us give a name to the plotted line
    plt.legend() # The legend function will display the chart's legend
    plt.xlabel('Time')
    plt.ylabel('Cases')
    plt.title('Timeline of cases per region')

plt.show()

Now, let's imagine we want to have individual charts for each region. Pyplot can create a grid to host various charts:

In [ ]:
fig, axes = plt.subplots(nrows = 2, ncols = 4, figsize = (20, 5))

Let's have a look at the previous statement: the `subplots` function takes number of rows and number of columns argument, as well as the size of each figure. Since we have 7 WHO regions, we will create a 2x4 grid. The `subplots` function returns two objects: `fig` which is the figures to host the plots, and `axes` which is an array of figure identifiers:

In [ ]:
fig

In [ ]:
axes

This might sound confusing right now, but it will make more sense with the exercise. Let's now create a list of tuples that we'll use as coordinates of our grid:

In [ ]:
plot_cols = list((l1, l2) for l1 in list(range(2)) for l2 in list(range(4)))
plot_cols

As you can see, each element of the list is a tuple with a pair of coodinates of 0 to 3 (x axis) and 0 to 1 (y axis). Let's now try to make these plots:

In [ ]:
fig, axes = plt.subplots(nrows = 2, ncols = 4, figsize = (20, 5))

# We use the zip operator to iterate simultaneously over two separate iterables.
# This way we can pair a region to a figure in each iteration:
for (region, plot_col) in zip(regions, plot_cols):
    data = df[df['WHO_region']==region].groupby('Date_reported').agg('sum')
    axes[plot_col].plot(data.index, data.Cumulative_cases)
    
plt.show()

Let's now add the other elements of the plots

In [ ]:
fig, axes = plt.subplots(nrows = 2, ncols = 4, figsize = (20, 5))

for (region, plot_col) in zip(regions, plot_cols):
    data = df[df['WHO_region']==region].groupby('Date_reported').agg('sum')
    axes[plot_col].plot(data.index, data.Cumulative_cases)
    #to add individual figure elements, we use the methods 'set_title()', 'set_ylabel()', 'set_ylabel()'
    axes[plot_col].set_title(region)
    axes[plot_col].set_xlabel('Time')
    axes[plot_col].set_ylabel('Number of cases or deaths')
    
plt.show()

It's not bad, but the titles and the axis labels are too crammed. Let's give them some space:

In [ ]:
fig, axes = plt.subplots(nrows = 2, ncols = 4, figsize = (20, 5))

for (region, plot_col) in zip(regions, plot_cols):
    data = df[df['WHO_region']==region].groupby('Date_reported').agg('sum')
    axes[plot_col].plot(data.index, data.Cumulative_cases)
    axes[plot_col].set_title(region)
    axes[plot_col].set_xlabel('Time')
    axes[plot_col].set_ylabel('Number of cases or deaths')
    
plt.subplots_adjust(hspace=0.5, wspace=0.5)
plt.show()

### Final exercise
Using the tools you've learned so far, choose a single WHO region (any) and make plots of cases timelines for each country in the region. Have fun!